#!/usr/bin/env bash
# Sync ai-main's shared voice and skills into a Hermes profile.

set -euo pipefail

AI_MAIN="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ACTUAL_HOME="${HOME:-$(printf '%s' ~)}"

# The Fedora gateway uses a dedicated HERMES_HOME. Prefer that service profile when
# it exists; callers can override it explicitly with AI_MAIN_HERMES_HOME.
if [ -n "${AI_MAIN_HERMES_HOME:-}" ]; then
    HERMES_TARGET_HOME="$AI_MAIN_HERMES_HOME"
elif [ "$(uname -s)" = "Linux" ] && [ -f "$ACTUAL_HOME/lekagents/hermes/profiles/personal/config.yaml" ]; then
    HERMES_TARGET_HOME="$ACTUAL_HOME/lekagents/hermes/profiles/personal"
elif [ -n "${HERMES_HOME:-}" ] && [ -f "$HERMES_HOME/config.yaml" ]; then
    HERMES_TARGET_HOME="$HERMES_HOME"
else
    HERMES_TARGET_HOME="$ACTUAL_HOME/.hermes"
fi

HERMES_CONFIG="$HERMES_TARGET_HOME/config.yaml"
SOUL="$HERMES_TARGET_HOME/SOUL.md"
MARKER="<!-- generated by ai-main hermes bridge; edit ai-main/config/hermes-soul.md -->"

fail() { printf '✗ %s\n' "$*" >&2; exit 1; }
ok() { printf '✓ %s\n' "$*"; }
warn() { printf '⚠ %s\n' "$*" >&2; }

[ -f "$HERMES_CONFIG" ] || fail "Hermes config not found: $HERMES_CONFIG"
[ -x "$AI_MAIN/bin/aimain" ] || fail "aimain is not executable: $AI_MAIN/bin/aimain"
command -v hermes >/dev/null 2>&1 || fail "hermes command not found in PATH"

printf 'ai-main: %s\nHermes home: %s\n' "$AI_MAIN" "$HERMES_TARGET_HOME"

# Keep generated full-tier sources current. This does not change tracked files.
"$AI_MAIN/bin/aimain" build >/dev/null

mkdir -p "$HERMES_TARGET_HOME"
if [ -e "$SOUL" ] && ! head -1 "$SOUL" 2>/dev/null | grep -qF 'generated by ai-main hermes bridge'; then
    backup_dir="$ACTUAL_HOME/.ai-backup-$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$backup_dir"
    cp -p "$SOUL" "$backup_dir/hermes-SOUL.md"
    warn "backed up existing Hermes SOUL.md to $backup_dir/hermes-SOUL.md"
fi

# SOUL is deliberately limited to identity and communication style. Workflow,
# project knowledge, and commands stay in AGENTS.md/.hermes.md and skills.
tmp_soul="$(mktemp "${SOUL}.tmp.XXXXXX")"
{
    printf '%s\n\n' "$MARKER"
    cat "$AI_MAIN/config/hermes-soul.md"
    printf '\n## Shared response style\n\n'
    cat "$AI_MAIN/build/full/style.md"
} > "$tmp_soul"
mv "$tmp_soul" "$SOUL"
ok "generated $SOUL"

# Hermes scans this directory alongside its native skills. Existing Hermes skills
# remain in the primary profile directory and win on name collisions.
# `hermes config set` stores scalars only, so write the YAML list directly.
# Build a symlink farm under build/hermes-skills (gitignored) that mirrors
# install.sh's "shippable skills only" selection: owned skills + every external
# pack skill except deprecated/, in-progress/, personal/, node_modules/.
HERMES_FARM="$AI_MAIN/build/hermes-skills"
rm -rf "$HERMES_FARM"
mkdir -p "$HERMES_FARM"

link_skill_farm() {
    local src="$1"
    [ -d "$src" ] || return 0
    local skill_md skill_name
    while IFS= read -r -d '' skill_md; do
        case "$skill_md" in
            */deprecated/*|*/in-progress/*|*/personal/*|*/node_modules/*) continue ;;
        esac
        skill_name="$(basename "$(dirname "$skill_md")")"
        ln -sfn "$(dirname "$skill_md")" "$HERMES_FARM/$skill_name"
    done < <(find "$src" -name SKILL.md -print0)
}
link_skill_farm "$AI_MAIN/skills"
link_skill_farm "$AI_MAIN/external/9arm-skills/skills"
link_skill_farm "$AI_MAIN/external/agent-skills/skills"
link_skill_farm "$AI_MAIN/external/mattpocock-skills/skills"

python3 - "$HERMES_CONFIG" "$HERMES_FARM" <<'PY'
import pathlib, re, sys
cfg_path, skills_dir = sys.argv[1], sys.argv[2]
cfg = pathlib.Path(cfg_path)
lines = cfg.read_text().splitlines()
out, i, patched = [], 0, False
while i < len(lines):
    line = lines[i]
    m = re.match(r'^(\s*)external_dirs:\s*(.*)$', line)
    if m and not patched:
        indent = m.group(1)
        out.append(f"{indent}external_dirs:")
        out.append(f"{indent}  - {skills_dir}")
        j = i + 1
        while j < len(lines) and re.match(r'^\s+-\s', lines[j]):
            j += 1
        i = j
        patched = True
        continue
    out.append(line)
    i += 1
if not patched:
    for idx, line in enumerate(lines):
        if re.match(r'^skills:\s*$', line):
            out.insert(idx + 1, "  external_dirs:")
            out.insert(idx + 2, f"    - {skills_dir}")
            patched = True
            break
if not patched:
    out.append("skills:")
    out.append("  external_dirs:")
    out.append(f"    - {skills_dir}")
cfg.write_text("\n".join(out) + "\n")
if not patched:
    raise SystemExit(1)
PY
ok "linked ai-main skill farm through skills.external_dirs"

# Redeploy registered workspace knowledge where the workspace exists on this host.
# This is intentionally best-effort: ai-main's registry is shared with the Mac.
if ! "$AI_MAIN/bin/aimain" deploy --all --sync; then
    warn "some registered workspaces were unavailable or protected; run aimain link for a local repo"
fi

printf '\nHermes bridge ready. Start a new session or restart the gateway to load SOUL and skills.\n'
